### ISSUE TITLE
Twitter Badge 

### ISSUE THREAD

**Issue by rohank2502** [nhcarrigan/nhcarrigan#11]
You can simply remove the Twitter badge which shows followers or I have one idea that you can rename Twitter to `Twitter follower` so that it will be clear !!

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Modify the `README.md` in the root project directory.
  - Remove `<a href="https://twitter.com/nhcarrigan" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/twitter/follow/nhcarrigan?color=purple&label=Twitter&logoColor=purple&style=social" /></a>` from line 23.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.
