### ISSUE TITLE
[FEAT] Enhance social media badges 

### ISSUE THREAD

**Issue by felixfaisal** [nhcarrigan/nhcarrigan#12]
# Feature Request

## Is your feature request related to a problem? Please describe:
The social media badges do not have the colors of that social media, For example blue for LinkedIn etc. Also we can add logo of these social media apps, 

## Describe the solution you'd like
We can add logo and color by just changing the parameters in the markdown link.

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Modify the `README.md` file
  - Update the social media badges to reflect the colours/styles of the respective pages.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.
