### ISSUE TITLE
[FEAT] remove the github followers count

### ISSUE THREAD

**Issue by schmelto** [nhcarrigan/nhcarrigan#9]
# Feature Request

## Is your feature request related to a problem? Please describe:

Due the github shows the followers already i would recommend to remove it in the reamde

## Describe the solution you'd like

removing the bade of the github followers

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Modify the `README.md` file in the root project directory
  - Remove `<img src="https://img.shields.io/github/followers/nhcarrigan?color=purple&logoColor=purple&style=social" />` from line 21

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.
